//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeMeuMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANNERSPUBLICITARIOS
    {
        public long IDBANNER { get; set; }
        public string TITULOCAMPANHA { get; set; }
        public string BANNERCAMPANHA { get; set; }
        public string LINKBANNER { get; set; }
    }
}
